# -*- coding: utf-8 -*-
"""Modelo preditivo - IAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVKly5apPt1gJSnWeGYZks6yntO3HcTt

#Importações
"""

# importações
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

"""#Carregar dados e ordenação"""

# carregar dados tratados
df = pd.read_excel('BASE_FINAL_TRATADA.xlsx')

# ordenação dos dados
df = df.sort_values(['Nome', 'Ano'])

"""#Dicionário de dados

| Coluna           | Descrição                                                     |
| ---------------- | ------------------------------------------------------------- |
| **Nome**         | Identificador anonimizado do aluno                            |
| **Ano**          | Ano da avaliação (2022, 2023, 2024)                           |
| **Data de Nasc** | Ano de nascimento do aluno                                    |
| **Idade**        | Idade do aluno no ano da avaliação                            |
| **Gênero**       | Sexo do aluno (Masculino/Feminino)                            |
| **Pedra**        | Fase educacional do aluno (Quartzo, Ágata, Ametista, Topázio) |
| **INDE**         | Índice geral de desempenho do aluno                           |
| **IAN**          | Índice de Adequação de Nível (mede defasagem)                 |
| **IDA**          | Índice de Desempenho Acadêmico                                |
| **IEG**          | Índice de Engajamento                                         |
| **IAA**          | Índice de Autoavaliação                                       |
| **IPS**          | Índice Psicossocial                                           |
| **IPP**          | Índice Psicopedagógico                                        |
| **IPV**          | Índice de Ponto de Virada                                     |
| **DELTA_IDA**    | Variação do desempenho acadêmico ao longo do tempo            |
| **DELTA_IEG**    | Variação do engajamento                                       |
| **DELTA_INDE**   | Variação da nota geral                                        |
| **ENG_X_DESEMP** | Interação entre engajamento e desempenho                      |
| **RISCO_FUTURO** | Variável alvo do modelo (1 = risco de defasagem futura)       |

#EDA

Visão geral da base
"""

df.info()
df.describe()

"""A base apresenta dados de alunos ao longo de múltiplos anos, contendo indicadores acadêmicos, comportamentais e psicossociais. Não foram identificados grandes volumes de dados ausentes após o processo de limpeza.

Distribuição dos indicadores
"""

import matplotlib.pyplot as plt

df[['IAN','IDA','IEG','IAA','IPS','IPP','IPV','INDE']].hist(figsize=(12,8))
plt.show()

"""Observa-se a distribuição dos principais indicadores, permitindo identificar concentração dos valores e possíveis assimetrias. Alguns indicadores apresentam maior dispersão, sugerindo heterogeneidade no perfil dos alunos.

Correlação entre variáveis
"""

import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

df.replace('INCLUIR', np.nan, inplace=True)
colunas = ['IAN','IDA','IEG','IAA','IPS','IPP','IPV','INDE']

for col in colunas:
    df[col] = pd.to_numeric(df[col], errors='coerce')

plt.figure(figsize=(10,6))
sns.heatmap(df[colunas].corr(), annot=True, cmap='coolwarm')
plt.title("Correlação entre indicadores")
plt.show()

"""Observa-se correlação positiva entre desempenho acadêmico (IDA), engajamento (IEG) e o índice geral (INDE), indicando que alunos mais engajados tendem a apresentar melhores resultados.
A análise também sugere que fatores psicossociais podem impactar indiretamente o desempenho.

Engajamento vs Desempenho
"""

sns.scatterplot(data=df, x='IEG', y='IDA')
plt.title("Engajamento vs Desempenho")
plt.show()

"""Existe uma tendência positiva entre engajamento e desempenho acadêmico, indicando que alunos mais engajados tendem a apresentar melhores resultados escolares.

#Feature Engineering
"""

# target
df['IAN_FUTURO'] = df.groupby('Nome')['IAN'].shift(-1)

# remover linhas sem futuro
df = df.dropna(subset=['IAN_FUTURO'])

# definir risco (mediana)
limite = df['IAN'].median()
df['RISCO_FUTURO'] = (df['IAN_FUTURO'] > limite).astype(int)

# variação ao longo do tempo
df['DELTA_IDA'] = df.groupby('Nome')['IDA'].diff()
df['DELTA_IEG'] = df.groupby('Nome')['IEG'].diff()
df['DELTA_INDE'] = df.groupby('Nome')['INDE'].diff()

# interação entre variáveis
df['ENG_X_DESEMP'] = df['IEG'] * df['IDA']

# preencher nulos gerados pelo diff
df.fillna(0, inplace=True)

"""#Features"""

features = [
    'IDA','IEG','IAA','IPS','IPP','IPV','INDE',
    'DELTA_IDA','DELTA_IEG','DELTA_INDE',
    'ENG_X_DESEMP'
]

X = df[features]
y = df['RISCO_FUTURO']

"""#Treino e Teste"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

"""#Modelo"""

model = RandomForestClassifier(
    n_estimators=400,
    max_depth=12,
    min_samples_split=5,
    class_weight='balanced',
    random_state=42
)

model.fit(X_train, y_train)

"""#Previsão e Avaliação"""

y_pred = model.predict(X_test)

# avaliação
print("Acurácia:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# importancia das variáveis
import matplotlib.pyplot as plt

importancias = pd.Series(model.feature_importances_, index=features)
importancias.sort_values().plot(kind='barh')

plt.title('Importância das Variáveis')
plt.show()

# resultado
df_resultado = X_test.copy()
df_resultado['Real'] = y_test
df_resultado['Previsto'] = y_pred

df_resultado.head()

"""#Modelo.pkl

"""

import pickle

with open('modelo_risco.pkl', 'wb') as f:
    pickle.dump(model, f)